apiVersion: v1
kind: Secret
metadata:
  name: piping-secret
stringData:
  OIDC_CLIENT_SECRET: 36DyRgfR6IEFIQb56tnC7VN8EIhJWQ4HhjsRwdPCrT5J
  ENCRYPTION_KEY: jOQgDRhe5Vo1SGzIb3TDWijBwdx+4uqv7+xMDRgaXUo=
